services:
  web:
    container_name: web
    platform: linux/amd64
    build:
      context: ./web/
      target: development
    entrypoint: ["sh", "-c", "pnpm config set store-dir /tmp/pnpm/store && pnpm install --frozen-lockfile && pnpm dev"]
    volumes:
      - ./web:/usr/src/vite
    ports:
      - 3000:3000
    networks:
        - hoshizora-network
    restart: always

  api:
    container_name: api
    platform: linux/amd64
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - 5000:5000
    networks:
        - hoshizora-network
    restart: always

  db:
    container_name: db
    platform: linux/amd64
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hoshizora
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
        - hoshizora-network
    restart: always

networks:
  hoshizora-network:
    name: hoshizora-network

volumes:
  db-data:
    name: db-data
