"""empty message

Revision ID: 54d6cdee8bfe
Revises: 
Create Date: 2024-10-26 22:44:50.368369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d6cdee8bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_url', sa.String(length=255), nullable=False),
    sa.Column('author', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('text', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('e_paper_devices',
    sa.Column('e_paper_id', sa.String(length=36), nullable=False),
    sa.Column('device_identifier', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('e_paper_id'),
    sa.UniqueConstraint('device_identifier'),
    sa.UniqueConstraint('e_paper_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('device_sessions',
    sa.Column('device_session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('e_paper_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['e_paper_id'], ['e_paper_devices.e_paper_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('device_session_id')
    )
    op.create_table('favorite_books',
    sa.Column('favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_books')
    op.drop_table('device_sessions')
    op.drop_table('users')
    op.drop_table('e_paper_devices')
    op.drop_table('books')
    # ### end Alembic commands ###
