/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/anonymous-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** フロントの接続 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    /** @description 既存セッションID */
                    sessionId?: string;
                };
            };
            requestBody: components["requestBodies"]["AnonymousLogin"];
            responses: {
                /** @description 接続成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["responses"]["AnonymousLoginResponse"][];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** お気に入りした本の取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    /** @description 既存セッションID */
                    sessionId?: string;
                };
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["BooksRetrieved"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /**
         * お気に入りに本を追加
         * @description 本のIDをお気に入りリストに追加します
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["AddFavorite"];
            responses: {
                201: components["responses"]["FavoriteAdded"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ランダムな本のIDと画像を取得
         * @description ランダムに選ばれた本のIDと画像データをBase64エンコード形式で返します
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["RandomBookData"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/qrcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** QRコードを取得 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["deviceIdentifier"];
            responses: {
                200: components["responses"]["QRCodeRetrieved"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "title": "こころ",
         *       "sentence": "私わたくしはその人を常に先生と呼んでいた。",
         *       "link": "https://www.aozora.gr.jp/cards/000148/files/773_14560.html",
         *       "date": "11月1日",
         *       "bookimage": "/9j/4AAQSkZJRgABAQEAAAAAAAD..."
         *     } */
        Book: {
            /** @description 本のタイトル */
            title?: string;
            /** @description 本の一文 */
            sentence?: string;
            /** @description 本が読めるリンク */
            link?: string;
            /** @description お気に入りした日時 */
            date?: string;
            /**
             * @description Base64エンコードされた画像データ
             * @example /9j/4AAQSkZJRgABAQEAAAAAAAD...
             */
            bookImage?: string;
        };
    };
    responses: {
        /** @description お気に入りの本一覧取得成功 */
        BooksRetrieved: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Book"][];
            };
        };
        /** @description お気に入り追加成功 */
        FavoriteAdded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description 追加成功メッセージ */
                    message?: string;
                    /** @description 追加された本のID */
                    bookId?: string;
                };
            };
        };
        /** @description ランダムな本のIDと画像データ */
        RandomBookData: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description ランダムに選ばれた本のID */
                    bookId?: string;
                    /** @description 画像データ(0~3) */
                    ePaperImage?: string;
                };
            };
        };
        /** @description QRコードの画像データ */
        QRCodeRetrieved: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description 画像データ(0~3) */
                    ePaperImage?: string;
                    /** @description 電子ペーパーのセッションID */
                    sessionId?: string;
                };
            };
        };
        /** @description セッションIDをCookieに設定して返却 */
        AnonymousLoginResponse: {
            headers: {
                /** @description セッションIDを含むCookie */
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description ログイン成功メッセージ */
                    message?: string;
                };
            };
        };
        /** @description サーバーエラー */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: {
        /** @description お気に入りに追加する本のID */
        AddFavorite: {
            content: {
                /** @example {
                 *       "bookId": "12345",
                 *       "sessionId": "sessionId"
                 *     } */
                "application/json": {
                    /** @description 追加する本のID */
                    bookId: string;
                    /** @description 電子ペーパーのセッションID */
                    sessionId: string;
                };
            };
        };
        /** @description 電子ペーパーID */
        ePaperId: {
            content: {
                /** @example {
                 *       "ePaperId": "12345"
                 *     } */
                "application/json": {
                    /** @description 電子ペーパーID */
                    ePaperId: string;
                };
            };
        };
        /** @description 電子ペーパーのMACアドレス */
        deviceIdentifier: {
            content: {
                /** @example {
                 *       "deviceIdentifier": "2ce14b7e-18e6-4f32-b66d-c9b6128744a8"
                 *     } */
                "application/json": {
                    /** @description 電子ペーパーのMACアドレス */
                    deviceIdentifier: string;
                };
            };
        };
        /** @description デバイスID */
        AnonymousLogin: {
            content: {
                /** @example {
                 *       "deviceId": "7d5f56e5-5769-43d2-b951-1f72f45a0c50"
                 *     } */
                "application/json": {
                    /** @description デバイスID */
                    deviceId: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
